# numpy

### attributes

In [1]:
import numpy as np

In [10]:
! pip install numpy                  

In [11]:
# creating an array

from list

In [12]:
list1=[1,2,3,4,5,6]

In [13]:
arr1=np.array(list1)

In [14]:
arr1

array([1, 2, 3, 4, 5, 6])

In [16]:
arr1.ndim #dimensions

1

In [17]:
tpl=(112,123,321)

In [19]:
arr2 = np.array(tpl)

In [20]:
arr2

array([112, 123, 321])

In [21]:
arr2.dtype # datatypes of elements

dtype('int32')

In [22]:
arr2.shape #rows x columns

(3,)

In [23]:
arr2.size # no of elements in array

3

In [24]:
arr2.ndim #dimensions

1

In [25]:
arr2.nbytes # memory occupied by the array

12

### creating different dimensional array

In [28]:
arr3=np.array([[4,5,6],[7,8,9]])

In [29]:
arr3

array([[4, 5, 6],
       [7, 8, 9]])

In [30]:
arr3.ndim

2

In [31]:
arr3.shape

(2, 3)

In [32]:
arr3.size

6

In [33]:
arr3.nbytes

24

In [34]:
arr3.dtype

dtype('int32')

### 3d array

In [41]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)

In [42]:
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [43]:
arr5=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],ndmin=4)

In [44]:
arr5

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

In [45]:
arr5.size

12

In [46]:
arr5.shape

(1, 1, 3, 4)

In [53]:
arr6=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

In [54]:
arr6.size

12

In [55]:
arr6.shape

(1, 3, 4)

In [56]:
arr6.ndim

3

### using range creating array

In [57]:
r=np.array(range(1,13),ndmin=4)

In [58]:
r.shape

(1, 1, 1, 12)

reshaping

In [61]:
n=r.reshape(1,1,1,12)

In [62]:
n

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [74]:
s=np.array(range(24))

In [75]:
s.shape

(24,)

In [76]:
p=s.reshape(1,1,1,24)

In [77]:
p

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
          15, 16, 17, 18, 19, 20, 21, 22, 23]]]])

In [78]:
print(p.ndim)

4


In [88]:
l=np.array(range(12))
print(l.ndim)
q=l.reshape(2,3,2)
print("/n",q)

1
/n [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [89]:
#create 3X3 array with only even values using range function

In [100]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [101]:
#linspace used to print specific number of values using range function
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [103]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [104]:
np.ones((2,3),dtype='int').reshape(3,2)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [106]:
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [105]:
np.full((4,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [4]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

### numpy random number

In [7]:
np.random.rand(12)  # uniformed values from 0 to 1

array([0.37960677, 0.9905714 , 0.04288663, 0.97319848, 0.28048588,
       0.4764906 , 0.05199327, 0.0906321 , 0.42598461, 0.75477776,
       0.64671227, 0.38664041])

In [9]:
np.random.rand(2,1)

array([[0.24100817],
       [0.06775152]])

In [10]:
np.random.randn(3,3)

array([[ 0.30367966,  0.89207974, -0.85082984],
       [-0.01131535, -0.86274454,  1.67866498],
       [-1.17841594, -0.32187648,  2.26580446]])

In [11]:
np.random.randint(1,10,size=(3,4))

array([[6, 4, 1, 6],
       [8, 2, 8, 5],
       [8, 1, 7, 4]])

In [13]:
np.random.randint(1,12,size=(3,3))

array([[7, 1, 1],
       [1, 6, 8],
       [9, 1, 9]])

In [15]:
np.random.uniform(12,11,size=(5,5))

array([[11.96449799, 11.39420328, 11.78167014, 11.93797796, 11.15026059],
       [11.96027608, 11.86611637, 11.9665286 , 11.35466939, 11.51153606],
       [11.44656276, 11.19861024, 11.93551677, 11.31621604, 11.93402467],
       [11.6655459 , 11.59648302, 11.98721003, 11.42369439, 11.31231754],
       [11.06003167, 11.99181887, 11.01372166, 11.76488163, 11.12128476]])

### random seed

In [19]:
np.random.seed(121)
np.random.randint(10,20,size=(6,5))

array([[12, 15, 18, 14, 11],
       [14, 13, 10, 12, 14],
       [16, 13, 19, 14, 19],
       [18, 16, 17, 15, 19],
       [19, 17, 13, 14, 18],
       [13, 14, 13, 14, 12]])

### indexing and slicing

In [24]:
s=np.arange(1,10)
s[:-3]

array([1, 2, 3, 4, 5, 6])

In [26]:
l=np.array(range(12,32),ndmin=2).reshape(4,5)

In [27]:
l

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31]])

In [29]:
l[1][2]

19

In [30]:
l[3,3]

30

In [31]:
l[2,1:3]

array([23, 24])

In [33]:
l[3,:-3]

array([27, 28])

### dimension change

In [43]:
r=np.array(range(12,32),ndmin=2).reshape(4,5)

In [44]:
r

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31]])

In [45]:
np.flip(r)

array([[31, 30, 29, 28, 27],
       [26, 25, 24, 23, 22],
       [21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12]])

In [46]:
np.fliplr(r)

array([[16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17],
       [26, 25, 24, 23, 22],
       [31, 30, 29, 28, 27]])

In [47]:
np.flipud(r)

array([[27, 28, 29, 30, 31],
       [22, 23, 24, 25, 26],
       [17, 18, 19, 20, 21],
       [12, 13, 14, 15, 16]])

In [49]:
np.rot90(r)

array([[16, 21, 26, 31],
       [15, 20, 25, 30],
       [14, 19, 24, 29],
       [13, 18, 23, 28],
       [12, 17, 22, 27]])

In [50]:
r.transpose()

array([[12, 17, 22, 27],
       [13, 18, 23, 28],
       [14, 19, 24, 29],
       [15, 20, 25, 30],
       [16, 21, 26, 31]])

### statistical measures

In [53]:
z=np.array(range(20,40))

In [54]:
z.mean()

29.5

In [55]:
z.var()

33.25

In [56]:
z.std()

5.766281297335398

In [57]:
z.max()

39

In [58]:
z.min()

20

In [64]:
np.median(z)

29.5

In [66]:
np.sum(z)

590

### mathematical operators on arrays

In [104]:
w=np.array(range(15,24),ndmin=3).reshape(3,3)
m=np.array(range(25,34),ndmin=3).reshape(3,3)

In [89]:
w,m **2

(array([[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[ 625,  676,  729],
        [ 784,  841,  900],
        [ 961, 1024, 1089]], dtype=int32))

In [83]:
w-m

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [84]:
w/m

array([[0.6       , 0.61538462, 0.62962963],
       [0.64285714, 0.65517241, 0.66666667],
       [0.67741935, 0.6875    , 0.6969697 ]])

In [85]:
w%m

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]], dtype=int32)

In [90]:
w+m

array([[40, 42, 44],
       [46, 48, 50],
       [52, 54, 56]])

### stacking and splitting

In [91]:
w

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [93]:
np.hstack((w,w,m))

array([[15, 16, 17, 15, 16, 17, 25, 26, 27],
       [18, 19, 20, 18, 19, 20, 28, 29, 30],
       [21, 22, 23, 21, 22, 23, 31, 32, 33]])

In [95]:
np.vstack((w,m))

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [96]:
np.dstack((w,m))

array([[[15, 25],
        [16, 26],
        [17, 27]],

       [[18, 28],
        [19, 29],
        [20, 30]],

       [[21, 31],
        [22, 32],
        [23, 33]]])

In [112]:
np.vsplit(m,3)

[array([[25, 26, 27]]), array([[28, 29, 30]]), array([[31, 32, 33]])]

In [114]:
np.hsplit(w,3)

[array([[15],
        [18],
        [21]]),
 array([[16],
        [19],
        [22]]),
 array([[17],
        [20],
        [23]])]

In [115]:
np.concatenate((w,m),axis=1)

array([[15, 16, 17, 25, 26, 27],
       [18, 19, 20, 28, 29, 30],
       [21, 22, 23, 31, 32, 33]])

In [6]:
a=3.14232
np.round(a,4)

3.1423

In [7]:
np.round(a)

3.0

In [8]:
np.round(a,2)

3.14

In [9]:
## floor
np.floor(a)

3.0

In [10]:
np.ceil(a)

4.0

### rounding functions

In [12]:
num=3.296511561216
np.round(num,3)

3.297

### ravel function

In [15]:
arr=np.array(range(1,16)).reshape(5,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [16]:
np.ravel(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
arr.ndim

2

In [25]:
l=np.array(range(12,57)).reshape(3,3,5)
l

array([[[12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26]],

       [[27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41]],

       [[42, 43, 44, 45, 46],
        [47, 48, 49, 50, 51],
        [52, 53, 54, 55, 56]]])

In [26]:
np.ravel(l)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56])

In [27]:
l.ndim

3

### set operations

In [31]:
ar1=np.arange(1,10)
ar2=np.arange(8,20)
print(ar1)
print(ar2)

[1 2 3 4 5 6 7 8 9]
[ 8  9 10 11 12 13 14 15 16 17 18 19]


In [34]:
### union
np.union1d(ar1,ar2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [35]:
## intersecting
np.intersect1d(ar1,ar2)

array([8, 9])

In [60]:
### for different dimensional arrays
ar3=np.array(range(1,9),ndmin=4).reshape(4,2)
print(ar3)
ar4=np.array(range(8,16),ndmin=4).reshape(4,2)
print(ar4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [39]:
np.setdiff1d(ar3,ar4)

array([1, 2, 3, 4, 5, 6, 7])

### array broadcasting

In [42]:
a=np.array(range(1,21)).reshape(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [43]:
a+8

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [44]:
a*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [45]:
a//2

array([[ 0,  1,  1,  2],
       [ 2,  3,  3,  4],
       [ 4,  5,  5,  6],
       [ 6,  7,  7,  8],
       [ 8,  9,  9, 10]], dtype=int32)

In [47]:
a/3

array([[0.33333333, 0.66666667, 1.        , 1.33333333],
       [1.66666667, 2.        , 2.33333333, 2.66666667],
       [3.        , 3.33333333, 3.66666667, 4.        ],
       [4.33333333, 4.66666667, 5.        , 5.33333333],
       [5.66666667, 6.        , 6.33333333, 6.66666667]])

In [48]:
a-4

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
a%5

array([[1, 2, 3, 4],
       [0, 1, 2, 3],
       [4, 0, 1, 2],
       [3, 4, 0, 1],
       [2, 3, 4, 0]], dtype=int32)

### filtering arrays

In [61]:
print(ar4)

[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [62]:
ar4[ar4>10]

array([11, 12, 13, 14, 15])

In [79]:
a=np.array(range(1,100))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [64]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [65]:
a[a%6==0]

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

### where() condition

In [74]:
np.where(a%5==0,"y","n")

array(['n', 'n', 'n', 'n', 'y', 'n', 'n', 'n', 'n', 'y', 'n', 'n', 'n',
       'n', 'y', 'n', 'n', 'n', 'n', 'y', 'n', 'n', 'n', 'n', 'y', 'n',
       'n', 'n', 'n', 'y', 'n', 'n', 'n', 'n', 'y', 'n', 'n', 'n', 'n',
       'y', 'n', 'n', 'n', 'n', 'y', 'n', 'n', 'n', 'n', 'y', 'n', 'n',
       'n', 'n', 'y', 'n', 'n', 'n', 'n', 'y', 'n', 'n', 'n', 'n', 'y',
       'n', 'n', 'n', 'n', 'y', 'n', 'n', 'n', 'n', 'y', 'n', 'n', 'n',
       'n', 'y', 'n', 'n', 'n', 'n', 'y', 'n', 'n', 'n', 'n', 'y', 'n',
       'n', 'n', 'n', 'y', 'n', 'n', 'n', 'n'], dtype='<U1')

In [82]:
l=np.array(range(1,50))
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [89]:
print(np.where(l<5))
print(np.where(l<20))

(array([0, 1, 2, 3], dtype=int64),)
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18], dtype=int64),)


### squeez and expand

#### isin()

In [92]:
a=np.array(range(1,10))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
b=[2,3,4]

In [93]:
np.isin(a,b)

array([False,  True,  True,  True, False, False, False, False, False])